### ISSUE TITLE
New Logistics order state needs a mapping to corresponding Retail order states

### ISSUE THREAD

**Issue by nirmay** [ONDC-Official/ONDC-Protocol-Specs#26] opened 2022-04-11 12:34 UTC
AS per #5 , 3 new states are added for logistics orders. In addition, logistics order also has a state "Active".
It is not clear, how each of these are mapped to corresponding states for Retail Order? 

Secondly, the Hyperlocal specification, currently, indicates following fulfillment states. 
`Describes how a single product/service will be rendered/fulfilled to the end customer. state can have following values - "Searching-for-Agent", "Assigned-Agent", "En-route-to-drop", "At-pickup-location", "At-drop-location", "Delivered-package", "Cancelled-package", "Returned-package"`
It is not clear how Logistics order states are mapped to the fulfillment.state specified above.

**Comment by BLR-0118** [comment] 2022-07-25 06:39
@nirmay pls check the updated Order & Fulfillment state for retail & logistics

**Comment by nirmay** [comment] 2022-07-25 15:52
@BLR-0118 Still not very clear,
I see that Retail spec now has State as a descriptor like struct, 
should the fulfillment.state.descriptor.name in retail order hold the order.state from Logistics order?

Why is fulfillment.state a struct like descriptor? if there is a valid reason, why is order.state (both Retail & Logistics) not following the same struct?

**Comment by BLR-0118** [comment] 2022-07-26 18:35
Fulfillment State is more detailed enums and has a struct like descriptor to support free text, images, etc. Order state is more concise and shows the internal state of the order. Order.state for retail & logistics will be almost same and so too would be the Fulfillment.state for retail & logistics. For now, these are the values:
Order.state (retail)
============
 Created
 Packed
 Shipped
 Out for Delivery
 Delivered
 RTO initiated
 RTO delivered
 Cancelled

Order.state (Logistics)
==============
Created
Out for Delivery
Delivered
RTO initiated
RTO delivered
Cancelled

Fulfillment State (Retail)
===============
 "Serviceable",
 "Non-serviceable",
 "Agent reached pickup",
 "Agent picked up order",
 "Agent reached drop location",
 "Agent delivered the order",
 "Order is cancelled"

Fulfillment State (Logistics)
=================
 "Searching for Agent",
 "Agent assigned",
 "Agent reached pickup",
 "Agent picked up order",
 "Agent reached drop location",
 "Agent delivered the order"
 "Order is cancelled"

Let's finalize this @nirmay

**Comment by nirmay** [comment] 2022-07-28 02:56
@BLR-0118 largely okay with this, some clarifications
- fulfillment state is referring to fulfillment.state.descriptor.name correct?
- I see that we have in Retail order states "Packed" and "Shipped", I am assuming Packed is when Seller marks it Ready to ship, but What about "Shipped" I see no corresponding state coming from Logistics? Is Logistics "Out of Delivery" mapped to Retail "Out of Delivery" or "Shipped". 

If we can clarify above points, we are good to go, thanks

**Comment by BLR-0118** [comment] 2022-07-28 05:15
1. Yes, fulfillment state is fulfillment.state.descriptor.name
2. "Packed" is when seller marks order as "ready to ship". 
3. Added "Shipped" to Logistics order state.

**Comment by umaswam1974** [comment] 2022-08-16 13:06
The order.state values for logistics have Out for delivery followed by Shipped. Isint this the other way around. ie shipped and then out for delivery.

Do we have equivalent state for retail Packed for logistics? Retail order has 8 stated whereas logistics has 7.

**Comment by BLR-0118** [comment] 2022-08-16 15:02
order.state and logistics.state are not in any particular order now. Will take care of this in the next update. 

Retail has "packed". You want an equivalent state for logistics? what should it be?
@umaswam1974

**Comment by poornimaaithal** [comment] 2022-08-17 05:31
What should be the fulfillment state when order is in "created" state (and ready_to_ship is still no)? 
Since fulfillment has not yet started can we return empty string in the fulfillment.state.descriptor.name?

**Comment by BLR-0118** [comment] 2022-08-17 05:41
I'm not sure. What do you suggest?
@poornimaaithal

**Comment by siva-digiit** [comment] 2022-08-17 06:29
@BLR-0118, pls confirm the values for items[].tags.status in retail /update and /on_update

**Comment by poornimaaithal** [comment] 2022-08-17 08:35
@BLR-0118 Since fulfillment is not yet started, we can either not send fulfillment state object at all or if everyone's assuming that fulfillment object is available all the time, we can send empty string in fulfillment.state.descriptor.name

**Comment by BLR-0118** [comment] 2022-08-17 18:21
I prefer not sending the fulfillment state at order creation.
@poornimaaithal

**Comment by BLR-0118** [comment] 2022-08-17 18:23
@siva-digiit - can you pls file a separate issue for that so we can get comments from others as well

> @BLR-0118, pls confirm the values for items[].tags.status in retail /update and /on_update

**Comment by siva-digiit** [comment] 2022-08-18 04:20
Hi Supriyo,

Good morning. I have submitted a new issue for this. Refer: https://github.com/Open-network-for-digital-commerce/ONDC-Protocol-Specs/issues/80

Thanks,
Siva
________________________________

**Comment by poornimaaithal** [comment] 2022-08-18 04:57
> I prefer not sending the fulfillment state at order creation. @poornimaaithal

Ok @BLR-0118.  We will not send any fulfillment state object when the order is not yet marked ready to ship

**Comment by nirmay** [comment] 2022-08-18 12:03
@BLR-0118 referring to your comment above, "I prefer not sending the fulfillment state at order creation."
@poornimaaithal is inerpreting this as not sending fulfillment.state not to be sent in on_status when ready to ship is not marked. 

I think these are 2 different things. In on_status we should either send fulfillment.state or not send for all cases. It should not be based on value of the field. What we are doing adds unnecessary complexity.

I propose, we include fulfillment.state in on_status calls always, if readytoship is not true, then leave it as empty, 

please comment?

**Comment by BLR-0118** [comment] 2022-08-18 12:52
order creation is /confirm and /on_confirm. However, fulfillment state needs to be sent in /on_status.
@nirmay @poornimaaithal

**Comment by poornimaaithal** [comment] 2022-08-18 12:58
Agree @nirmay @BLR-0118 
We need descriptor.name for this state @BLR-0118

**Comment by BLR-0118** [comment] 2022-08-18 13:15
When fulfillment hasn't started yet, can we use "Pending"?
@poornimaaithal @nirmay

**Comment by poornimaaithal** [comment] 2022-08-18 13:36
We can use "Pending" state and we can send this in on_confirm as well - because order will be in the same state in on_confirm and on_status(when ready to ship is still no)

**Comment by nitinmish** [comment] 2022-09-16 06:42
> Fulfillment State is more detailed enums and has a struct like descriptor to support free text, images, etc. Order state is more concise and shows the internal state of the order. Order.state for retail & logistics will be almost same and so too would be the Fulfillment.state for retail & logistics. For now, these are the values:
> 
> Order.state (retail): Created Accepted In-progress Completed Cancelled Packed (deprecated) Shipped (deprecated) Out for Delivery (deprecated) Delivered (deprecated) RTO initiated (deprecated) RTO delivered (deprecated)
> 
> Order.state (Logistics): Created Accepted In-progress Completed Cancelled Out for Delivery (deprecated) Shipped (deprecated) Delivered (deprecated) RTO initiated (deprecated) RTO delivered (deprecated)
> 
> Fulfillment State (Retail): "Serviceable", "Non-serviceable", "At pickup location", "Order picked up", "At drop location", "Order delivered", "RTO Initiated" "RTO Delivered" "Cancelled"
> 
> Fulfillment State (Logistics): "Searching for Agent", "Agent assigned", "At pickup location", "Order picked up", "At drop location", "Order delivered" "RTO Initiated" "RTO Delivered" "Cancelled"
> 
> Let's finalize this @nirmay

Is it mandatory to put fullfilment status as part of order object? If a tracking link is provided with the on_confirm, status can be picked up in real time through an open API. Just a thought. Suggestion is front loading a lot of processable information in the json.

**Comment by umaswam1974** [comment] 2022-09-16 16:57
@BLR-0118 We can send the order states as mentioned.
As far fulfillment  states, we cannot send 'At pickup location' and "At drop location' for self shipping. For logistics, if the logistics bpps provide the states, then we can relay them back.

Fulfillment State (Retail):"Serviceable","Non-serviceable","At pickup location","Order picked up","At drop location","Order delivered","RTO Initiated","RTO Delivered","Cancelled"

**Comment by BLR-0118** [comment] 2022-09-17 07:58
For self-delivery, the following fulfillment states can't be provided - At pickup location, At drop location. Hence, we'll remove these.

**Comment by BLR-0118** [comment] 2022-09-17 08:03
Order & fulfillment states are mandatory in Order object. Also, state changes trigger certain actions on the part of participants & hence need to be pushed in real-time e.g. if Order state becomes "In-Progress", order cancellation won't be allowed.
Also, /track supports callback URL which many buyer apps won't allow in their apps for security reasons.
@nitinmish

**Comment by BLR-0118** [comment] 2022-09-17 08:04
Final values for Order & Fulfillment State:

Order.state (retail):
 Created
 Accepted
 In-progress
 Completed
 Cancelled

Order.state (Logistics):
Created
Accepted
In-progress
Completed
Cancelled

Fulfillment State (Retail):
 "Serviceable"
 "Non-serviceable"
 "Order picked up"
 "Order delivered"
 "RTO Initiated"
 "RTO Delivered"
 "Cancelled"

Fulfillment State (Logistics):
 "Searching for Agent"
 "Agent assigned"
 "Order picked up"
 "Order delivered"
 "RTO Initiated"
 "RTO Delivered"
 "Cancelled"

All other values are deprecated

**Comment by BLR-0118** [comment] 2022-09-17 08:06
@umaswam1974 @nirmay @siva-digiit @poornimaaithal

**Comment by ONDC-Tech** [comment] 2022-09-17 08:32
Added to API contract & closing this issue

**Closed by ONDC-Tech** 2022-09-17 08:32 UTC

**Comment by Girisuta** [comment] 2022-09-19 10:49
Can we please get the definitions for each order state : 
Order.state (retail):
Created
Accepted
In-progress
Completed
Cancelled
@BLR-0118

**Comment by BLR-0118** [comment] 2022-09-19 14:39
Please check the API contract doc [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit) - specifically, the /confirm API
@Girisuta @varun-nf

**Comment by Girisuta** [comment] 2022-09-19 15:48
Copying the Definition from the API contract comments so that the details are in same place : 
Final list of enums for Order.state (retail):
Created - when created by the buyer app;
Accepted - when confirmed by the seller app;
In-progress - when order is ready to ship;
Completed - when all fulfillments completed
Cancelled - when order cancelled

**Comment by umaswam1974** [comment] 2022-09-22 15:27
@BLR-0118 , please clarify this.

Fulfillment states (Logistics) are the ones that logistics BPP sends back to logistics BAP (aka retail BPP)
Fulfillment states (Retail) are the ones that retail  BPP(aka logistics BAP) sends back to retail BAP.
So I would like to map the fulfillment states received from logistics BPP to the fulfillment states to be sent to retail BAP here as follows.
Fulfillment state(Logistics)                                 Fulfillment state (Retail)
Pending                                                             Pending
Searching-For-Agent                                         Packed
Agent assigned                                                  Packed
Order-picked-up                                                 Order-picked-up
--------------------                                                   Out-for-delivery
Order-delivered                                                  Order-delivered
Cancelled                                                           Cancelled

As seen above, when will I send out-for-delivery to retail BAP? There is no equivalent logistics fulfillment state.

**Comment by BLR-0118** [comment] 2022-09-22 16:23
@umaswam1974 added

**Comment by Jasraj-kripalani** [comment] 2022-09-25 13:40
@BLR-0118 Breaking the states into Order & Fulfillment makes a lot of sense. However, I feel that the order & fulfillment states should be defined on an order item level rather than on a parent order level. Many ecom companies ship out a single order into multiple packages. This could be done for various reasons. Few examples -  
- One item is fragile & needs a special postage method whereas the other item could be sent via speed post
- One item is made to order & needs more time to be shipped whereas the other item is ready & is shipped out immediately 
- Items are kept in different warehouses & therefore possibly have different fulfillment journeys & SLA's Eg. one can reach the same day whereas the other needs 3 days to reach the customer
- RTO can be triggered for only one of the items. 

In all these cases keep a state object for the parent order could lead to miscommunication between NP's & possibly incorrect UI elements being rendered for users on the Buyer Apps. 

Lastly, while this might not be the right thread of this suggestion I am adding it here as it's closely linked to logistics states -
Payment states should also be on an order item level as one order can be associated with multiple payments. Eg. Lets take an example of a COD order with multiple packages. The user will pay for the items as the packages arrive. Updating the payment state to "PAID" for the whole order in this case might again lead to confusion. Keeping the payment state as "UNPAID" might also not be the best solution. 

Please do correct me if my understanding is incorrect. Awaiting your inputs.

**Comment by BLR-0118** [comment] 2022-09-25 16:04
Agree. An order can have multiple fulfillments and each fulfillment could be for a single or multiple items. It covers all use cases mentioned above. Also, a logistics order will be for a single fulfillment. The COD payment mentioned above will be taken into consideration with the upgraded version of the base protocol.
@Jasraj-kripalani
